### ISSUE TITLE
listtransaction, listsinceblock missing/incomplete transactions

### ISSUE THREAD

**Issue by AhmedMSedeek** [decred/dcrwallet#1017]
Applies to v 1.1.2

listtransactions, listsinceblock RPC calls do not show the following transactions:

- receive transactions to an address that has been previously used in ticket purchases
- split transaction for ticket purchases
- revoke transactions for missed tickets

ticket transactions shows as two transactions

1 with vout 1 with address null
1 with vout 2 with dummy change address
vout 0 is not shown which is important to know ticket address

**Comment by jrick** [comment]
The wallet only cares about and will only save and list transactions that directly involve it.  You didn't mention which wallet you made these queries on, but if you have separate ticket purchasing and voting wallets, the voting wallet will, for example, not be aware of the split transaction because it does not spend or produce any outputs controlled by it.

**Comment by AhmedMSedeek** [comment]
I tried this on dcrwallet command prompt version on windows
I used testnet and the same wallet is used for ticket purchases as well as voting

**Comment by AhmedMSedeek** [comment]
@jrick Can you check please?

**Comment by jrick** [comment]
try gettransaction instead. listtransactions only lists by default the most recent transactions

**Comment by jrick** [comment]
I can't reproduce with the latest wallet.  Please reopen or create a new issue with a detailed example and output if you still see this.
