### ISSUE TITLE
bad help cmd causes wallet rpc connection reset and wallet lock

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#109]
Using the help cmd, followed by a invalid cmd, causes a wallet rpc connection reset, as well as a wallet lock which will block stake votes when the user thinks their wallet is unlocked. This is also true if help is typed for a valid cmd, but the cmd seems to just not have a help method.

> help setaccount
-8: No help for method 'setaccount'
> help walletlockdf
-8: No help for method 'walletlockdf'

12:36:07 2016-03-14 [INF] CHNS: Established connection to RPC server localhost:9109
12:36:24 2016-03-14 [INF] CHNS: Established connection to RPC server localhost:9109

**Comment by jolan** [comment]
I just tried to reproduce this on testnet and could not.  So it appears either the wallet was never unlocked or there's more that needs to happen for the unintended wallet locking to occur.

**Comment by jrick** [comment]
Additionally, those logs are not from you losing the websocket connection and dcrwallet reconnecting to dcrd.  It's because it create a new client (HTTP POST, not websocket) that sends another help rpc to dcrd.  It has to use HTTP POST because the help texts are different depending on the type of client.  The logs show because dcrwallet uses a dcrrpcclient package global logger, which the HTTP POST client is also using.

**Comment by raedah** [comment]
Ill see if I can reproduce again. Would help is there was a command to get the wallets current lock status.
