### ISSUE TITLE
Watching only wallet should generate unsigned transactions

### ISSUE THREAD

**Issue by cjepson** [decred/dcrwallet#111]
The watching only wallet should return unsigned transactions for the user to sign and submit using the cold wallet. The old JSON commands/results can be reused because they return a string. Instead of the transaction hash, the raw bytes of the transaction encoded as hex should be returned.

**Comment by jrick** [comment]
This functionality can be useful for hot wallets too.  I'd introduce this as a new rpc rather than overloading the behavior of another.

There also may not be a clear distinction between whether a wallet is hot or not.  Consider a hot wallet where another xpub is added to watch for transactions related to another wallet.

You may want to wait until the next btcwallet sync before implementing this.  The reason is that the new transaction creation code there does not need to repeatedly sign the transaction in order to determine whether the estimated fee is sufficient.

**Comment by vctt94** [comment]
Is this still desirable?

**Comment by jrick** [comment]
yes

**Comment by jrick** [comment]
Closing.  Creating the unsigned tx can be done with createrawtransaction, and the change output (and fee estimation) can be performed by fundrawtransaction.
