### ISSUE TITLE
Commands which involve listing addresses should not include pool

### ISSUE THREAD

**Issue by davecgh** [decred/dcrwallet#113]
Currently the commands which involve listing addresses produce addresses that are in the upcoming address pool and past the current address index.

For example `getaddressesbyaccount`, on  a freshly created wallet, ends up showing 20 addresses because they were generated in order to satisfy the gap limit and search for existing funds in order to sync.

The correct behavior would be to make sure that the commands only include addresses before the current address index (which is of course the next address that will be produced when queried).

**Comment by chappjc** [comment]
Sounds great, but I didn't know there was this 20 address gap limit.  Say I did something silly like generating 30 addresses I didn't use and then started using addresses after that.  It would be impossible to rebuild my wallet from seed and capture those higher addresses without hacking the code.

**Comment by davecgh** [comment]
It's not impossible.  You could recover without hacking the code by manually generating enough addresses, stopping the wallet, and then using the `dropwtxmgr` tool to force a rescan of all addresses from the genesis block.

I've mentioned before in IRC that the gap limit should be configurable in order to make it easier to recover both for the special cases like the one you're mentioning and some other where a higher gap limit makes sense such as a high volume store front.  Also, I've mentioned previously that there should probably be an RPC to effectively do the same thing as the manual process I described above.

That said, you can pretty much always break something by doing silly things, but realistically a gap limit is required because it's simply not feasible to generate and register 2^64-1 address at startup.  Without it, you'd have to ask the user a question like "What do you think the highest address index you used was?" in order to recover and of course that is way more error prone than a gap limit.

In practice, the default gap limit works extremely well for the vast majority of cases.  Making it configurable would allow it to be configured to work equally well in all cases.

**Comment by chappjc** [comment]
It's perfectly clear once you have an idea of how building a wallet works by address scanning.

I commented because this is a very important detail that I did not see in any documentation or announcements.  IRC is off my radar -- has been for two decades now -- but it sounds like it's the place to be.

Anyway, a **configurable gap limit seems valuable**.

**Comment by cjepson** [comment]
The variable to alter is here:
https://github.com/decred/dcrwallet/blob/master/wallet/wallet.go#L869-L877

There will be a PR later today that slackens rescanning tolerances and fixes a bug that was introduced on the btcwallet sync that caused gaps to be generated.

In the future I think we should consider a manual full wallet rescan RPC command or startup flag that drops the wtxmgr and has a configurable gap limit. If you change that constant, this should not be too bad. I think it is better suited as a startup flag instead of an RPC command, because it will probably take a very long time.

**Comment by davecgh** [comment]
Agreed that is the variable for the configurable gap limit.  However, this issue is really about what is produced by the RPC commands for which that number doesn't really apply.

**Comment by cjepson** [comment]
Right, yeah. Got a little off topic. I'll look into this one after the latest resync fixes are into.

**Comment by jrick** [comment]
Closing and merging with #411.  This will be a non-issue after that is finished.
