### ISSUE TITLE
Consolidate feature returns -22: TX rejected: tried to spend zero value output from input

### ISSUE THREAD

**Issue by David00** [decred/dcrwallet#128]
I have not seen any reports of this in the forum, but this seems to be an issue to me.  The transaction referenced is a standard ticket purchase.  I have tried reducing the number to consolidate down to 10 and it still gets hung up on that same txid.  Anything less than 10 and it throws a different error.

C:\Users\David\Desktop\DECRED\windows-amd64>dcrctl --wallet consolidate 9999 default
-22: TX rejected: tried to spend zero value output from input 3cb95a12623e44c89b4dc5081de9bde1a47501beb6a223ed63b0347ad053b101, idx 2

**Comment by chappjc** [comment]
It was reported in https://github.com/decred/dcrwallet/pull/61#issuecomment-195477553, but it should be fixed in 0.0.8.  You may need to recreate from seed and be very sure dcrd is done loading before starting dcrwallet for the first time.  In the forum, [a related discussion](https://forum.decred.org/threads/ticket-purchases-being-denied.1327/).  Have you tried these resolutions?

**Comment by David00** [comment]
Thanks - I just came across that thread... my first search on the issue returned no results.  I will try that and update.

**Comment by David00** [comment]
I started fresh with a new copy of the blockchain and re-imported the wallet from seed, and this fixed the issue.  Thank you for the help chappjc.  Closing issue!
