### ISSUE TITLE
listsinceblock rpc call not showing 0 confirmations transactions

### ISSUE THREAD

**Issue by santins77** [decred/dcrwallet#1309]
Since I have updated to version 1.3.0 the behaviour of listsinceblock rpc call has changed and is not showing transactions with 0 confirmations. This change is not documented in the changelog of the version.
When I call listtransactions I can see those transactions so they are already in the blockchain

**Comment by jrick** [comment]
I can not reproduce this behavior, nor do I see any changes that may have introduced this bug.  Are you certain the wallet knows about the tx?  Try querying it with gettransaction.

**Comment by jrick** [comment]
Also keep in mind that listsinceblock takes an optional parameter to specify the minimum number of confirmations for included results.  The default is 1, and you would need to set it explicitly to 0 to see anything that is unmined.

**Comment by jrick** [comment]
Nevermind, I see what is causing this.  A target confirmations of zero is disallowed because it would make the listblock field in the result ambiguous.  [Bitcoind does the same thing](
https://github.com/bitcoin/bitcoin/blob/86e0a33f5c382513d5179e3fdf158baf952d7e2f/src/wallet/rpcwallet.cpp#L1603).  This doesn't look like a bug at all, and sorry if the behavior was changed without it being clear from the release notes.

**Comment by santins77** [comment]
As long as we have seen bitcoin list unconfirmed transactions. The parameter just ensures that the last_block returned has the number of confirmations indicated by the minimum number of confirmations. The field last_block is totally independent of the list of transactions returned by the command.

**Comment by jrick** [comment]
That's correct, sorry. bitcoind does not use it as a result filter, while we are (and shouldn't).

**Comment by adamcollier1** [comment]
Do you plan to alter this so that **listsinceblock** includes mempool transactions? bitcoind does return mempool transactions in this call.
