### ISSUE TITLE
Proposal: Serving gRPC Methods via REST and Websocket RPC APIs with JSON

### ISSUE THREAD

**Issue by jozn** [decred/dcrwallet#1378]
I want to implement this functionality but needs teams green flag to work on this.

this feature will let developers have access to gRPC methods with REST+JSON API and potentiality with Websocket+JSON RPC. This can increase 3rd party developer adaptation.

How it will be done?
I will write a custom code generator, this code generator will read .proto file and extracts messages and RPC methods in the protocol buffer file. Then it will produce:
- for each pb message: a struct type specific for JSON, this struc will be similar to what protocol buffer but bytes in josn structs will be a string (hex or base64 encoding).
- for each pb message: a converter between original pb struct type and our json struct will be produced.
- for each pb rpc method: add to map http router for accessing  gRPC method from REST api.
- and more for websocket, types converting,...

Benefits: 
- REST, JSON, Websocket is universal and most of the developer are comfortable with these technologies. gRPC is hard for many people and specially it is difficult for scripting languages. This API can increase 3rd party developer adaptation of Decred.
- Single source of trust: both gRPC and REST will be served from the same implementation of rpc
- Codebase will be statically type-safe,there will little to zero of `interface{}` 
- Codebase will be a snapshot our `.proto` file
- Adding a new rpc to gRPC will be as before, this code generator will produce all codes for achieving what has been proposed in here, they just need to run this code generator alongside gRPC generator. 

Caveats:
- bytes will be converted to hex(or base64), so the developer who access gRPC methods must with REST api will use the hex string of it's binary 
- the most important caveats are stream rpc: in REST api we should return an error, stream api cannot be handled over REST, but we can for those rpc methods whic are not in form of push notification or long running stream we can add a no-stream api method of equivalent functionality. stream rpc are will be fully working.

Some notes:

- json spec has not any integer number limits but javascript has an accurate integer number limit of ( 2**54)-1 which is smaller than total atoms of Decred. Anyway Go has not such problems and it's json packages will produce number exactly as they are in Go environment. So numbers is %100 safe.
- the heavy lifting of serving gRPC methods over REST and Websocket will be in the code genratoer.

I can implement an experimental fully working draft of this functionality in 2-3 weeks. 
If you have any question regarding this lets me know.

**P.S**: to clarify this code generator will map incoming Http REST and Websocket requests and converte them in such a way that can be handled with existing gRPC methods and then return the result of gRPC methods in an appropriate manner to API consumer.

**Comment by davecgh** [comment]
Are you aware that there is already a legacy RPC server which serves JSON?

**Comment by jozn** [comment]
Hi Dave, thanks for your response. 
Yes, I'm aware of that legacy API, and before I seriously consider implementing these features I made my research into the difference between gRPC and that API. that API was the first API gateway of the dcrwallet and is more or less compatible with bitcoin API. gRPC's of dcrwallet provides more methods, some of which are unique to decred. gRPC is a modern version of decred API.
What I want to do is exposing this API's to developers in a way that most of them are already familiar with. This feature is simple in its nature, just grab request at the 
This feature can be an experimental attempt, I PR the functionality and you can decide whether you want  to take this route. I can submit PR of the working draft of this in the next week and improve it after that. 
I like to join the decred team and I think adding this a good way to start, after implementing this I will work on other issues and improvements.

https://github.com/jozn/pb_walker : This is a gRPC like, a code generator for software that I was working on, it is similar to gRPC but with custom code output to better handle our stacks. The code generator that I will build for dcrwallet will be based on this.

**Comment by davecgh** [comment]
Alright, cool.  I just wanted to make sure you were aware of it since I didn't see it mentioned in the original issue.

For the record, I don't really work on wallet very much as my focus is elsewhere, however, I personally completely agree with you about gRPC in general not being the most friendly for 3rd parties to consume, particularly for scripts.  Even more than that though, the fact that raw bytes for things like blocks and transactions are sent means the consumer has to also implement all that serialization code.  It is true that, in many cases, the consumer is going to need to do that anyway, but there area lot of smaller applications that can get by just fine by making use the already structured data typically provided by JSON-RPC/REST.

I'm speaking from experience there as I've written quite a few little handy utilities that I personally use that make use of for various things in Go, for which there are already excellent modules from dcrd for serialization and the like, but have found that consuming the gRPC is a huge burden as compared to doing the same thing via the `rpcclient` which uses `JSON-RPC`.

So, given all of that, I personally would have zero qualms with providing feature complete JSON-RPC (though I would highly suggest using JSON-RPC 2.0 and avoiding positional params) and REST APIs that include Decred additions.  Obviously, I would think it would still need to maintain the legacy API for all of those applications that depend on it.

All of that said, we'll want some of the folks who actively work on dcrwallet to chime in.

**Comment by jozn** [comment]
Thanks, I have already been working on this feature. And I'm sure the legacy API should be maintained too.

**Comment by jrick** [comment]
I'm not particularly sold on this idea due to the added complexity it would introduce.

Why not use an established solution like https://github.com/grpc-ecosystem/grpc-gateway, which (from what I can tell) does everything you are proposing, automatically, using a separate proxy server?

**Comment by jozn** [comment]
Thanks, Josh for your feedback.
I made a mistake that saying I'm going to serve it over with REST. What actually originally I had in mind was for serving gRPC over HTTP and WebSocket JSON-RPC. This is much less complicated and doesn't require those kinds of complexity that grpc-gateway will brings.

As longs as serving gRPC methods over HTTP and WebSocket RPC be desirable, there will be no problems in terms of complexity and maintainability. There won't be any change to the existing codebase. I strive for maximum simplicity, maintainability, and automation. I still doing some research for achieving the best result.

Stay tuned, I will inform you of the process.

**Comment by jozn** [comment]
In this case, I prefer to postpone working on this issue and start working on other active issues.
You can close this.
