### ISSUE TITLE
Ticket purchases should use new txauthor package for improved fee estimation

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#141]
This should improve bad experiences such as #140 where the fees are unexpectedly high.  Output consolidation will still be needed for some dusty wallets, but improving the fee estimation will reduce the number of these cases.

The txauthor package is intentionally flexible as to what kinds of transactions it can create (it takes a slice of outputs, rather than addresses) so I expect it would be easy to switch over to that API for other transaction types.

**Comment by davecgh** [comment]
Agreed.  The new txauthor package is a very nice improvement over the old code and it makes a lot of sense to convert the code over to use it.

**Comment by cjepson** [comment]
Agreed, it's TODO for me to rewrite most of that code as it is a disaster. Tickets can be generated most efficiently by first generating an output that is exactly the size required for a new ticket from any number of inputs, and then the ticket itself. Because of how tickets are constructed, for an individual stake miner this actually incurs less fees and simply buying the ticket with more UTXOs. It also allows the change to be immediately spent on a new ticket.

**Comment by raedah** [comment]
I had the same experience as #140.

**Comment by alexlyp** [comment]
#183 Adds this functionality
