### ISSUE TITLE
Scientific notation

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrwallet#15]
There are a few places where the rpc server returns scientific notation that should probably be decimal to be consistent with everything else.  This was pointed out by Emilio Mann on the forum:

fee in listtransactions

paytxfee and relayfee in getinfo

**Comment by davecgh** [comment]
While I'm certainly not against this, I would like to point out that scientific notation is perfectly valid JSON.

See the number section at http://www.json.org/

**Comment by jcvernaleo** [comment]
Yep, I know it is valid json, but it is inconsistent with other output (in the same command even) and this is probably a case where decimal is a more useful format (despite my general preference for scientific notation in non-monetary cases).

**Comment by jrick** [comment]
Good luck solving this one while not ditching encoding/json.  We've looked into it before and came up empty handed.

I'd also like to voice my opinion that users should never be reading the raw json output of an rpc response.  A json parser should be used to unmarshal the json into a form that can be printed with the correct numerical notation.

**Comment by jyap808** [comment]
In Bitcoin, this is implemented using the ValueFromAmount function in rpcserver.cpp.

``
UniValue ValueFromAmount(const CAmount& amount)
{
    bool sign = amount < 0;
    int64_t n_abs = (sign ? -amount : amount);
    int64_t quotient = n_abs / COIN;
    int64_t remainder = n_abs % COIN;
    return UniValue(UniValue::VNUM,
            strprintf("%s%d.%08d", sign ? "-" : "", quotient, remainder));
}
``

**Comment by jrick** [comment]
Looks like json.Number can be used.

https://godoc.org/encoding/json#Number

**Comment by jrick** [comment]
http://play.golang.org/p/Lg2LO3RR26

**Comment by jyap808** [comment]
Yeah looks good to me.

**Comment by jrick** [comment]
Unfortunately this would mean we'd have to change all of the json struct types to use json.Number instead of int64.  And since the same types are used for both encoding and decoding, now a client using our "nice" types have to explicitly convert every json.Number to an integral value, AND remember to check the error (which really should have happened earlier during the initial unmarshal).

I think the cleanest solution would be to switch any int64 amount to dcrutil.Amount and make that type a json.Marshaler/Unmarshaler, but I've discussed that with @davecgh before and he does not want json code in the util package, and in go it is impossible to attach behaviors (methods in this case) to types from another package.

**Comment by jcvernaleo** [comment]
Based on jrick's comments (from admittedly a long time ago) and the fact that we've been able to live with this for so long I don't see us changing it unless there is serious outcry so I'm closing this issue.  Of course if anyone feels super strong they can always reopen it for discussion again (or even better, open on btcwallet so it could happen upstream).
