### ISSUE TITLE
createtemp and appdata options output misinformation 

### ISSUE THREAD

**Issue by githubsands** [decred/dcrwallet#1655]
`--createtemp` and  `--appdata` options output misinformation when there exists no configuration, `dcrwallet.conf`, within the specified appdata directory 

```
./dcrwallet --createtemp --appdata=~/temp
2020-01-30 19:40:59.347 [WRN] DCRW: open ~/temp/dcrwallet.conf: no such file or directory
Tried to create a temporary simulation wallet for network other than simnet!

```

`Tried to create a temporary simulation wallet for network other than simnet!` should not output

**Comment by jrick** [comment]
I don't know why you are calling this misinformation.  The missing config is only a warning, and the path in the missing config warning is correct because you changed the appdata directory where it is searched for.  The --createtemp help usage also mentions it is for creating a "simulation wallets" implying usage is only valid with --simnet, and the following error message confirms this.
