### ISSUE TITLE
fee api is inconsistent

### ISSUE THREAD

**Issue by toddfries** [decred/dcrwallet#171]
getwalletfee
5000000
settxfee 2000000
true
getwalletfee
200000000000000
settxfee .02
true
getwalletfee
2000000

**Comment by raedah** [comment]
I think its also worth a reminder note here that 'help settxfee' describes this as 'the increment used each time more fee is required', as opposed to what most users would assume, that its setting the outgoing tx fee. The description leaves much to be desired, as I don't know under which conditions the increment will occur.

**Comment by jrick** [comment]
The required fee is a proportion based on the transaction size.  For a 0.01 fee, that's actually 0.01/kB.  If you only construct a 500 byte transaction, the required fee only needs to be 0.005.

This value is also no longer used as an increment (it was in previous versions), so that help should be updated.
