### ISSUE TITLE
listtransactions "account"

### ISSUE THREAD

**Issue by tpruvot** [decred/dcrwallet#175]
> dcrw-cli  listtransactions default
> -4: Transactions are not yet grouped by account
> 
> jy-p> is that an existing issue on github? you should file it if not

**Comment by vctt94** [comment]
Can I get this one?

**Comment by vctt94** [comment]
Right now the error message is `transactions can not be searched by account`. If this is the expected behavior, I think this message is accurate, isn't it?

**Comment by jrick** [comment]
It's accurate but it doesn't reflect the fact that the feature has no plans to be implemented (for us) or was intentionally removed (for bitcoin core).  The only valid parameter that can be used is `*` to reference all accounts.  Unfortunately, the account name is the first parameter, and because we use positional JSON-RPC arguments, we can't simply remove the parameter from the API without breaking backwards compatibility.
