### ISSUE TITLE
settxfee allows setting below required amounts

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#187]
```
> settxfee 0     
true
> getwalletfee
0
```

But when trying to do a transaction, this error comes up.
-32603: -22: TX rejected: transaction --- has 0 fees per kb which is under the required threshold amount of 1000000

The expected behavior would be to have a minimum value that settxfee is allowed to be set to, and to return an error telling the user that they can not set the txfee below the minimum amount, and tell them what the minimum amount is.

Also wondering, why are the set and get cmds for this feature spelled differently?

**Comment by raedah** [comment]
Related to issue https://github.com/decred/dcrwallet/issues/171 and its pr https://github.com/decred/dcrwallet/pull/172 where a user could end up accidentally setting a txfee that is way too high, I suggest a safe guard upper bound sane limit on what txfee can be set as well.

**Comment by alexlyp** [comment]
I disagree that the expected behaviour would be for a minimum to be set internally.

If people want to set these fees to wacky values, that's their responsibility to use sensible numbers.  The nodes/miners will accept deny based on their own rules

Even if we did have an internal lower/upper bound, what would those bounds be?

**Comment by alexlyp** [comment]
Well actually after talking with devs a bit more about it, I think coming up with a sensible upper bound makes sense to avoid people setting fees to a crazy number.

But there will be no lower bound, if people want to set them all the way to 0 then so be it.

**Comment by raedah** [comment]
@alexlyp Low fee's are already invalid. Error: "TX rejected: transaction has 0 fees per kb which is under the required threshold amount of 1000000". Instead of letting a user set it to a value which is going to cause an error later, it would be more helpful to just let them know when they try to set it that it is not going to work.

**Comment by alexlyp** [comment]
Well problem there is that err is not coming from wallet, that is a dcrd mempool fee threshold acceptance err.  The tx fails due to the rules set therein, there is nothing limiting you (nor should there be) in wallet from sending a tx that has fees that are below the threshold

**Comment by raedah** [comment]
What is the use case for for sending a transaction with fees below the mempool fee threshold?

**Comment by jrick** [comment]
You could be using a newer version of dcrd which lowers the default relay fee, or you changed the relay fee policy from a config option.  dcrd and dcrwallet are two distinct projects and they need to be able to work together when the other is using non-standard options.

**Comment by alexlyp** [comment]
dcrd PR https://github.com/decred/dcrd/pull/124 fixes the ability to send transactions with too high of fees.  If a user wishes to skip this check they can set --allowhighfees=true, otherwise it will always check to see that the fee isn't greater than 100x of the min fee.

And I think the devs are in agreement that adding a check in wallet for too low of fees would work against the centralization of mempool policy in daemon.  Thanks for opening the issue, nonetheless.

**Comment by raedah** [comment]
+1:
