### ISSUE TITLE
Create wallet from single command line command

### ISSUE THREAD

**Issue by SG-O** [decred/dcrwallet#19]
It would be great if GUIs could create wallet's from a simple command line command. At this moment it is almost impossible to create wallets from anything but the command line, because stdio emulation won't work when asked for passwords.

**Comment by jrick** [comment]
I solved this issue, but in another way, for the new grpc api in btcwallet (which dcrwallet should get soon).  The rpc server includes methods to dynamically create new or open existing wallets.  Once done, a new service is started so that the wallet can be interacted with by the rpc client.

**Comment by SG-O** [comment]
I noticed that piece of code when reading through the btcwallet code. It still would be great if there could also be a similar command in the legacy Json rpc command set, so I won't have to write a rpc implementation again.
Also it shouldn't be too hard to add a command to create the wallet only with command line options. One could easily adapt the "createSimulationWallet" function into doing that, I think.

**Comment by marcopeereboom** [comment]
We have decided that we are not going to add this.

**Comment by jrick** [comment]
We'll take a patch that adds this to the json-rpc server but it's not a priority for us.

That said, we absolutely don't want to add wallet creation using command line flags, since these are readable by other processes.  Here's a short powershell script that demonstrates the issue:

```
$timespan = new-object System.Timespan(0, 0, 1)
$query = new-object System.Management.WqlEventQuery(
        "__InstanceCreationEvent",
        $timespan,
        "TargetInstance ISA 'Win32_Process' AND TargetInstance.Name='dcrwallet.exe'")
$watcher = new-object System.Management.ManagementEventWatcher($query)

$event = $watcher.WaitForNextEvent()
$event.TargetInstance.CommandLine
```

```
PS C:\Users\jrick> & .\walletwatcher.ps1
"dcrwallet" --testnet --noinitialload --experimentalrpclisten=127.0.0.1:19112 --onetimetlskey --appdata="C:\Users\jrick\AppData\Local\Decred\Paymetheus"
```

That particular command line has the flags that Paymetheus is using to start dcrwallet with.  I started the script, and it waited until I started Paymetheus, and then in response to that event, printed all of the command line args.  You can imagine that if we were to add flag-based wallet creation as well, it would be insecure since secrets (such as seeds, the encryption key, etc) would be visible to other processes.
