### ISSUE TITLE
enablestakemining starts on 2nd block

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#199]
With enablestakemining=1, looks to me like it doesn't start purchasing tickets till after its received the first block of the new stake period. So then it sends out the purchase tx, and you then get confirmed into the next block (hopefully), but the first opportunity is missed.

**Comment by cjepson** [comment]
Problem is two-fold. There's a mempool bug that causes a 1 block lag, and a wallet bug that uses current stake difficulty rather than next difficulty. Another mempool bug probably causes incorrect rejection of transactions because it compares current stake difficulty instead of next block stake difficulty. Hopefully we'll get these off by one bugs cleaned up soon.

**Comment by jrick** [comment]
This isn't a wallet bug.
