### ISSUE TITLE
No error if dcrwallet cannot read specified config file

### ISSUE THREAD

**Issue by chappjc** [decred/dcrwallet#233]
When using `-C/--configfile`, if dcrwallet does not have permissions or the file is misspelled (missing) there is no error or warning, but the settings from the intended config file are not read.

**Comment by jrick** [comment]
Thanks for the report.  The error is handled with a warning but this is done with a call to the logger before it has been initialized (logger initialization depends on the values in the config).  It will need to print the warning to standard error instead.

**Comment by jrick** [comment]
I'd also think we should make this a fatal error instead of simply a warning.  The only exception to this would be if the value was left untouched by the user.

When btcsuite/btcwallet#434 is reviewed, merged, and synced with dcrwallet, this will become possible.  Currently we don't have the ability to determine whether a flag was explicitly set to a default value vs being unchanged by a flag or config setting.

**Comment by chappjc** [comment]
A similar problem exists with dcrctl, but I haven't double checked and made the issue.

**Comment by jrick** [comment]
Cool, thanks for checking that out too.  Definitely needs to be fixed.

I opened a btcwallet PR that fixes this upstream, and if we can get that in in the next couple of days, we can pick it up in the next sync (merge currently planned for monday).

**Comment by chappjc** [comment]
Any update on this?

This is starting to look like a real headache for PoS pools, as the  pooladdress, and ticketaddress must be correct or tickets go "missing" or invalid and it becomes the operator's problem to add them manually if possible or refuse.

**Comment by jrick** [comment]
The upstream PR that fixes this is still under review: https://github.com/btcsuite/btcwallet/pull/446

**Comment by chappjc** [comment]
Thanks.  I don't mean to be pushy.  :)  The issue applies to all three dcr tools.

**Comment by jrick** [comment]
Fixed by #631
