### ISSUE TITLE
Wallet needs to block notifications while handling rescans

### ISSUE THREAD

**Issue by cjepson** [decred/dcrwallet#350]
If the wallet doesn't block and wait to handle block notifications while doing the first time rescan on restore from seed, corruption will result. Rescans should block notifications on startup.

**Comment by jrick** [comment]
After briefly looking into this, I did not see a quick way to fix it.  The notification channel can not be not read, because doing so would mean also blocking all notifications required for the rescan (rescanprogress, rescanfinished, and all transaction notifications created from the rescan itself).  I am of the mind that all syncing logic needs a significant rewrite, and should be moved out of the wallet package at that time.

**Comment by jrick** [comment]
This is a non-issue with the new rescan code.
