### ISSUE TITLE
Address field of a listunspent result only includes the first address associated with the pkscript

### ISSUE THREAD

**Issue by chappjc** [decred/dcrwallet#370]
This is known but I have not seen an issue for it.  Code:

https://github.com/decred/dcrwallet/blob/master/wallet/wallet.go#L2576

``` go
// BUG: this should be a JSON array so that all
// addresses can be included, or removed (and the
// caller extracts addresses from the pkScript).
if len(addrs) > 0 {
    result.Address = addrs[0].EncodeAddress()
}
```

**Comment by jrick** [comment]
This would be a breaking change to the JSON-RPC server API, which we have far less flexibility to diverge from since it would break clients written with the Bitcoin Core API in mind.  I'm unsure what the rest of the team wants to do here but I'm fine not doing anything.  We want to focus on our gRPC API instead.

**Comment by chappjc** [comment]
It's not anything I need or want, but I though it should be noted.
