### ISSUE TITLE
Stake voting with locked wallet

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#392]
Pregenerate and save locally the vote transaction signature data for your tickets so that your wallet does not need to be unlocked in order to do PoS voting (and revoking). 

For redundant PoS voting servers, the dcrwallet data files can easily be rsync'd over, and once the dcrwallet process is restarted the user would not need to unlock the wallet.

**Comment by raedah** [comment]
I will add to this, maybe second phase, that the transaction generation can be done on an offline machine. Then the presigned transactions would be syncronized to the nodes. I imagine this would happen either via an api, or (probably more secure) via a file that stores the data.

**Comment by davecgh** [comment]
The problem with any kind of pre-generation scheme is that you would have to cast votes a certain way before you know what they mean.  I know that currently it doesn't seem like that big of a deal since there is really only a single bit which votes on the validity of the previous block, however, before too much longer (within the next 2 to 3 release I believe is what the roadmap shows), vote transactions will actually be doing more than just voting on the previous block.  They will be voting on whether or not consensus changes which constitute a hard fork take effect.

As I'm sure people interested in this already know, when you purchase a ticket, it might not be selected as a winner for up to ~4.7 months.  Within that period, new block and stake versions which redefine the meaning of the vote bits very well could become active.  That means the vote has to understand the exact current state when it is actually cast.  Any type of pre-generation/pre-signing scheme can't guarantee that.

What I would personally much rather see is a separate "voting account" of sorts which houses the target addresses of the ticket purchases and has the necessary distinct privs required to sign and cast the votes independent of the wallet being unlocked.  Since a ticket, by design, does not contain any spendable funds, the worst that could happen by having your "voting account" unlocked and comprised is somebody could potentially cast a vote different than from what you really wanted.  Since the ticket contains the commitment, those funds can't be stolen.  It's the exact same model as stake pools in that regard where they simply can't steal the funds, but they could choose to vote against your wishes since voting rights have been given, except the system and wallet would have to be compromised for the potential to even exist in the "voting account" cases whereas it always exists with stake pools.

With this scheme, all spendable funds would independently require the wallet to be unlocked whereas the voting could commence independently with a locked wallet.

**Comment by jrick** [comment]
Votes also must contain the block height they vote on, so it's not feasible to pregenerate votes for all possible situations.
