### ISSUE TITLE
walletinfo rpc command output

### ISSUE THREAD

**Issue by karamble** [decred/dcrwallet#533]
https://github.com/decred/dcrwallet/blob/master/rpc/legacyrpc/methods.go#L3333-L3359

The command now have to output new variables for stakemining parameters:
enablevoting
enableticketbuyer

**Comment by jrick** [comment]
Because I was confused about this until it was explained over irc, the walletinfo rpc returns whether or not the "enablestakemining" feature of dcrwallet is enabled, but this feature was deprecated and replaced by the two new settings listed above, and these new settings are not reflected in the info.  We should add them.

**Comment by karamble** [comment]
Yeah, the walletinfo command is the only way to find out the current txfee of the wallet, as there is no gettxfee command, so i think this command is more essential to be accurate than it appears on the first look.

**Comment by jolan** [comment]
Closed via #599.
