### ISSUE TITLE
tx insufficient priority

### ISSUE THREAD

**Issue by feeleep75** [decred/dcrwallet#70]
sometimes when trying to send coins I got this message:

E0078: RPC method did not return 200 OK: Address: xxxxxxxxxxxxxxxxxxx ERROR: Response error or empty: -22: TX rejected: transaction def2d3bea20f8928e359c218c64cd210f967a434d7a5d5d9a5edc9c1e500a232 has insufficient priority (2.529764803846154e+07 <= 5.76e+07)

**Comment by cjepson** [comment]
This is a holdover from Bitcoin. In Bitcoin, to prevent spam, coin age is used as a rate limiter to prevent someone from making a spam transaction chain. This may end up being removed from Decred eventually, since Decred simply sets spam thresholds in fee amounts instead. This makes more sense, as you can assume a miner will want a certain amount of fees regardless of how old a transaction's inputs are.

**Comment by alexlyp** [comment]
This has been fixed with proper priority checks in dcrd now
