### ISSUE TITLE
Ticketbuyer defaults for the new sdiff algo

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#868]
This is about new defaults that people want on the ticket buyer, given the behavior of the new sdiff algo. People have been chatting about this, so creating an issue to track. 

Here are some ideas.
-Revert spreadticketpurchases back again so that it defaults to off
-Default maxperblock to 1
-Default maxfee to 0.01 so that buys do not happen when the fee goes up

**Comment by davecgh** [comment]
I think there could still be merit in `spreadticketpurchases` defaulting to on.  The ticketbuyer is likely to see artificial competition with them all trying to purchase tickets at the beginning of a round and pay more fee than would otherwise be necessary.

I do see your proposed settings here attempt to address that with a `maxfee` and `maxperblock`.  Those settings both seem reasonable to me.
