### ISSUE TITLE
Change HDCoinType from 20 to 42

### ISSUE THREAD

**Issue by jpz** [decred/dcrwallet#945]
In BIP44, it is published that Decred coin type = 42, and the derivation path should be m/44'/42'/

https://github.com/satoshilabs/slips/blob/master/slip-0044.md 

Presently, HDCoinType is defined to be 20, which leaves the derivation path to be m/44'/20'/ and this is not in accordance with the understanding of the rest of the community:

https://github.com/decred/dcrd/blob/f11fac8134626768ef7b1f278fd4331f004bfb49/chaincfg/params.go#L636

Multicurrency wallets are going to want to follow this standard pretty closely, which may lead to a lack of compatibility between Decred’s wallet and other wallets and future integration issues with multi-currency wallets generally.

To make this change however, we will want to be able to recover Decred that may exist in the old /20' wallet, and perhaps treat the old /20' path derivation wallets as legacy and read-only.

How this would be handled gracefully from a UI perspective in Decrediton/Paymetheus is something to consider, however I do see that Decrediton has support for "imported" (effectively read-only) wallets (i.e. it is not possible to generate receive addresses for the Imported wallet), so perhaps the Decrediton treatment would be similar to this and fairly simple to add.

Lastly, wallet.decred.org also has a default 20' derivation for wallets, so this default too would need to be updated.

**Comment by davecgh** [comment]
I agree this needs to happen.  I have previously suggested that the simplest way to handle it is to perform two independent scans on import/rescan.

The first would scan the old 20' path and the second one would scan the registered 42' path.  All new addresses would be generated with the registered path and all old ones would be treated as read only.  Doing this would allow it to happen transparently to the user.

**Comment by jrick** [comment]
A database upgrade is going to be required in order to make this transition.  Here's the general idea on how I plan on handle this:

A database upgrade will introduce a new metadata field that records the xpriv for the m/44'/42' key.  Upgraded databases will not record anything in this value.  Newly created databases will derive both the m/44'/20' and m/44'/42' coin type keys from the seed and save both of them.  When a newly created database runs the upgrade, if the field is already exists, nothing is done.

When both of the m/44'/20' and m/44'/42' xpriv keys exist in the database, the m/44'/20' key will be preferred for backwards compatibility.

An API will be added to delete either of the m/44'/20' or m/44'/42' keys.  This will allow the address discovery code to remove the keys that it doesn't end up using.

All future calls to access the coin type key will check both fields and return the one key

If the upgrade to the m/44'/42' key from the m/44'/20' key is performed, all keys that were saved and derived by the m/44'/20' xpiv, such as the coin type xpub and all account child keys, must be regenerated.

The upgrade to coin type 42 should error if any addresses have been derived for any accounts derived by the coin type 20 key.

**Comment by jrick** [comment]
I have most of the code for this change completed but this only applies to mainnet.  Testnet uses coin type 11 and simnet uses 115.

According to https://github.com/satoshilabs/slips/blob/master/slip-0044.md, coin type 1 should be used for testnet (and i presume other testing networks such as regtest, simnet, etc.).  We need to decide whether to only do the coin type upgrade on mainnet or if we want to switch the other two networks to use coin type 1 as well.

Personally I would be for this change since it would remove our coin type conflicts with NuShares and Ecoin as well as keeping the mainnet code similar to testnet (one common source of bugs I've been noticing is from doing different things depending on what network is active).
